# Generated by Django 5.1.4 on 2024-12-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
